[package]
name = "borger"
version.workspace = true
edition.workspace = true

[features]
server = ["tokio"]
client = ["atomicbox"]
session_replay = ["dep:serde", "glam/serde"]
singlethreaded = []

[dependencies]
borger_procmac = { path = "../procmac" }

log.workspace = true
glam.workspace = true
rapier3d.workspace = true

web-time = { version = "*", default-features = false }
num_enum = { version = "*", default-features = false }
wasm_thread = { git = "https://github.com/buttercrab/wasm_thread.git", branch = "patch-1", default-features = false, features = ["es_modules"] } #https://github.com/chemicstry/wasm_thread/pull/33

#server only
tokio = { version = "*", optional = true, default-features = false }

#client only
atomicbox = { version = "*", optional = true, default-features = false }
serde = { version = "*", optional = true, default-features = false, features = ["std", "derive"] }
