[package]
name = "server"
version.workspace = true
edition.workspace = true

[features]
server = ["borger_plugin_sdk/server", "borger/server", "game/server_internal_only_dont_use"]

#do not use. this is for nicer rust-analyzer support only
client = ["borger_plugin_sdk/client", "borger/client", "game/client_internal_only_dont_use"]
session_replay = []
singlethreaded = []

[dependencies]
borger_plugin_sdk = { path = "../plugins/sdk/rs" }
borger = { path = "../engine" }
game = { path = "../.." }

log.workspace = true

tokio = { version = "*", default-features = false, features = ["rt", "macros", "net", "time", "fs", "io-util", "sync"] }
wtransport = { version = "*", default-features = false, features = ["ring", "self-signed"] }
simple_logger = { version = "*", default-features = false, features = ["colors"] }
clap = { version = "*", default-features = false, features = ["std", "derive", "color", "error-context", "help", "suggestions", "usage"] }
tokio-tungstenite = { version = "*", default-features = false, features = ["rustls-tls-webpki-roots"] }
tokio-rustls = { version = "*", default-features = false }
futures-util = { version = "*", default-features = false }
