import { SIZEOF_32BIT } from "@borger/ts/networked_types/primitive.ts";

const NET_SIMULATION_PING = 0; //rtt/2 ms
const NET_CONNECTION_TIMEOUT = 10; //kill a websocket connection after this many seconds of lag. should match net.rs

export type State = {
	transport: WebTransport | WebSocket;
	newClientSnapshot: Uint8Array;
	writeInput: (tx: Uint8Array<ArrayBuffer>) => void;
	stateStream: AsyncGenerator<Uint8Array, void, unknown>;
	oops?: string;
};

export async function init(
	hostname: string,
	wtPort: number,
	wsPort: number,
	useWebTransport: boolean,
	onStateReceivedCB: Promise<(stateBuffer: Uint8Array) => void>,
	userCancel: Promise<void> | void,
): Promise<NetResult<State>> {
	let connection: Omit<State, "newClientSnapshot" | "error">;
	let disconnectPromise: Promise<string>;
	let succeeded = false;

	//user can only cancel if the game returns a promise in its
	//impl of onConnectionChange, and if the connection hasn't
	//already succeeded
	const userCancelGuard = new Promise<void>(function (resolve) {
		if (userCancel instanceof Promise) {
			userCancel.then(function () {
				if (!succeeded) resolve();
			});
		}
	});

	if (useWebTransport) {
		const config: WebTransportOptions = {};
		if (import.meta.env.DEV) {
			//this is autogenerated by the dev server when it starts
			try {
				const devcert: number[] = JSON.parse(await (await fetch("/devcert.json")).text());
				config.serverCertificateHashes = [{ algorithm: "sha-256", value: new Uint8Array(devcert) }];
			} catch {
				return { type: NetResultType.Err, result: "Can't fetch devcert.json" };
			}
		}

		const wt = new WebTransport(`https://${hostname}:${wtPort}`, config);
		userCancelGuard.then(() => wt.close());
		disconnectPromise = wtListenOnDisconnect(wt.closed);

		const readyResult = await result(true, wt.ready, disconnectPromise, userCancelGuard);
		if (readyResult.type !== NetResultType.Ok) return readyResult;

		const simulationStream = await result(
			true,
			wt.createBidirectionalStream(),
			disconnectPromise,
			userCancelGuard,
		);
		if (simulationStream.type !== NetResultType.Ok) return simulationStream;

		const inputStream = simulationStream.result.writable.getWriter();

		connection = {
			transport: wt,
			writeInput(stateBytes) {
				//write the number of bytes being sent
				const stateSizeBytes = new ArrayBuffer(SIZEOF_32BIT);
				new DataView(stateSizeBytes).setUint32(0, stateBytes.byteLength, true);

				inputStream.write(stateSizeBytes);
				inputStream.write(stateBytes);
			},
			stateStream: wtListenForState(simulationStream.result.readable.getReader()),
		};
	} else {
		const ws = new WebSocket(`wss://${hostname}:${wsPort}`);
		userCancelGuard.then(() => ws.close());
		ws.binaryType = "arraybuffer";
		const disconnectPWR = Promise.withResolvers<string>();
		disconnectPromise = disconnectPWR.promise;

		ws.onclose = function (e) {
			if (
				import.meta.env.DEV &&
				!succeeded &&
				confirm(
					"Lost connection to game server. Your browser may be blocking the WSS connection due to the server using self-signed certificates. Click OK to check.",
				)
			) {
				//using setInterval in an attempt to give the browser
				//more time to add the current vite page to its history.
				//sometimes since the page doesn't fully load before this
				//redirect, it doesn't get added. the websocket page
				//attempts to go back 1 page in history after dismissing
				//the cert warning so it needs to be in there
				setInterval(() => (location.href = `https://${hostname}:${wsPort}`), 500);
				return;
			}

			disconnectPWR.resolve(formatError({ reason: e.reason, closeCode: e.code }, false));
		};

		const openResult = await result(
			false,
			new Promise<void>((resolve) => (ws.onopen = () => resolve())),
			disconnectPromise,
			userCancelGuard,
		);
		if (openResult.type !== NetResultType.Ok) return openResult;

		connection = {
			transport: ws,
			stateStream: wsListenForState(ws, disconnectPWR.resolve),
			writeInput: ws.send.bind(ws),
		};
	}

	if (NET_SIMULATION_PING > 0) {
		const ogWriteInput = connection.writeInput;
		connection.writeInput = async function (chunk) {
			await new Promise((resolve) => setTimeout(resolve, NET_SIMULATION_PING));
			ogWriteInput(chunk);
		};
	}

	//the first packet is needed to init the simulation.
	//it is a snapshot of the current game state
	const newClientSnapshot = await result(
		useWebTransport,
		connection.stateStream.next().then((next) => next.value!),
		disconnectPromise,
		userCancelGuard,
	);
	if (newClientSnapshot.type !== NetResultType.Ok) return newClientSnapshot;

	const ret = { ...connection, newClientSnapshot: newClientSnapshot.result };
	disconnectPromise.then((oops) => (ret.oops = oops));
	onStateReceived(ret.stateStream, onStateReceivedCB);
	succeeded = true;
	return { type: NetResultType.Ok, result: ret };
}

//do not await this. it is an infinite loop
async function onStateReceived(
	stateStream: State["stateStream"],
	cbPromise: Promise<(stateBuffer: Uint8Array) => void>,
) {
	const cb = await cbPromise;
	while (true) cb((await stateStream.next()).value!);
}

export enum NetResultType {
	Ok,
	Err,
	UserCancel,
}

type NetResult<T> =
	| { type: NetResultType.Ok; result: T }
	| { type: NetResultType.Err; result: string }
	| { type: NetResultType.UserCancel };

async function result<T>(
	isWebTransport: boolean,
	succeed: Promise<T>,
	fail: Promise<string>,
	userCancel: Promise<void>,
): Promise<NetResult<T>> {
	try {
		const ok: Promise<NetResult<T>> = succeed.then((result) => ({ type: NetResultType.Ok, result }));
		const err: Promise<NetResult<T>> = fail.then((result) => ({ type: NetResultType.Err, result }));
		const userCancelMap: Promise<NetResult<T>> = userCancel.then(() => ({
			type: NetResultType.UserCancel,
		}));
		return await Promise.race([ok, err, userCancelMap]);
	} catch (oops) {
		return { type: NetResultType.Err, result: formatError({ reason: String(oops) }, isWebTransport) };
	}
}

function formatError(oops: WebTransportCloseInfo, isWebTransport: boolean) {
	let reason = oops.reason?.trim(); //sometimes it's nothing but whitespace?
	reason = reason ? `: ${reason ?? ""}` : "";

	const protocol = isWebTransport ? "WebTransport" : "WebSocket";
	const code = oops.closeCode !== undefined ? ` (${protocol} error code ${oops.closeCode})` : "";
	return `Lost connection to game server${reason}${code}`;
}

//---WEBTRANSPORT---//

//the equivalent "listen_for_input" happens in rust
async function* wtListenForState(stateStream: ReadableStreamDefaultReader) {
	let excess = new Uint8Array();

	while (true) {
		//receive number of bytes in server's simulation state diff
		const stateSizeBytes = await wtReceivePacket(stateStream, SIZEOF_32BIT, excess);
		const stateSize = new DataView(stateSizeBytes.packet.buffer).getUint32(0, true);
		excess = stateSizeBytes.excess;

		const stateBytes = await wtReceivePacket(stateStream, stateSize, excess);
		excess = stateBytes.excess;
		yield stateBytes.packet;
	}
}

async function wtListenOnDisconnect(closedPromise: Promise<WebTransportCloseInfo>) {
	let closeInfo;
	try {
		closeInfo = await closedPromise;
	} catch (oops) {
		closeInfo = { reason: String(oops) };
	}

	return formatError(closeInfo, true);
}

//stoopid api doesn't let you request to read
//a fixed number of bytes, so prvExcessBuffer
//is needed to hold onto whatever extra bytes
//were uncontrollably vomited
async function wtReceivePacket(
	stream: ReadableStreamDefaultReader,
	size: number,
	prvExcessBuffer: Uint8Array<ArrayBuffer>,
) {
	const packetBuffer = new Uint8Array(size);
	packetBuffer.set(prvExcessBuffer.subarray(0, size));
	let progress = prvExcessBuffer.length;

	let newExcessBuffer: typeof prvExcessBuffer;
	if (progress >= size) {
		newExcessBuffer = prvExcessBuffer.subarray(size);
	} else {
		while (progress < size) {
			if (NET_SIMULATION_PING > 0)
				await new Promise((resolve) => setTimeout(resolve, NET_SIMULATION_PING));

			const result = await stream.read();
			if (result.done) throw Error("State stream closed");

			const needMore = size - progress;
			packetBuffer.set(result.value.subarray(0, needMore), progress);
			progress += result.value.length;

			if (progress >= size) newExcessBuffer = result.value.subarray(needMore);
		}
	}

	return { packet: packetBuffer, excess: newExcessBuffer! };
}

//---WEBSOCKET---//

async function* wsListenForState(ws: WebSocket, timeoutResolver: (error: string) => void) {
	//buffer incoming messages so the async generator can yield them on demand
	const queue: Uint8Array[] = [];
	let resolve: (() => void) | null = null;
	let timeout = wsListenOnDisconnect(ws, timeoutResolver);

	ws.onmessage = (e: MessageEvent) => {
		queue.push(new Uint8Array(e.data as ArrayBuffer));
		resolve?.();
		resolve = null;

		clearTimeout(timeout);
		timeout = wsListenOnDisconnect(ws, timeoutResolver);
	};

	while (true) {
		if (queue.length === 0) await new Promise<void>((r) => (resolve = r));
		if (NET_SIMULATION_PING > 0) await new Promise((r) => setTimeout(r, NET_SIMULATION_PING));

		yield queue.shift()!;
	}
}

function wsListenOnDisconnect(ws: WebSocket, timeoutResolver: (error: string) => void) {
	return setTimeout(function () {
		timeoutResolver(formatError({ reason: "Timed out" }, false));
		ws.onmessage = null;
		ws.close();
	}, NET_CONNECTION_TIMEOUT * 1000);
}
