import { SIZEOF_32BIT } from "@borger/ts/networked_types/primitive.ts";

const NET_SIMULATION_PING = 0; //rtt/2 ms
const NET_TIMEOUT = 10; //kill a connection after this many seconds of lag. should match net.rs

type InitializingNetState = WTInitializingNetState | WSInitializingNetState;

type WTInitializingNetState = {
	transport: WebTransport;
} & InitializingNetStateRest;

type WSInitializingNetState = {
	transport: WebSocket;
} & InitializingNetStateRest;

type InitializingNetStateRest = {
	hostname: string;
	wtPort: number;
	wsPort: number;
	established: boolean;
	open: boolean;
	onDisconnect: [() => void];
};

export type State = Awaited<ReturnType<typeof init>>;

export async function init(hostname: string, wtPort: number, wsPort: number, useWebTransport: boolean) {
	let initState: InitializingNetState;
	let stateStream: AsyncGenerator<Uint8Array, void, unknown>;
	let writeInput: (stateBytes: Uint8Array<ArrayBuffer>) => void;

	if (useWebTransport) {
		const config: WebTransportOptions = {};
		if (import.meta.env.DEV) {
			//this is autogenerated by the dev server when it starts
			const devcert: number[] = JSON.parse(await (await fetch("/devcert.json")).text());
			config.serverCertificateHashes = [{ algorithm: "sha-256", value: new Uint8Array(devcert) }];
		}

		const transport = new WebTransport(`https://${hostname}:${wtPort}`, config);

		initState = {
			hostname,
			wtPort,
			wsPort,
			transport,
			established: false,
			open: true,
			onDisconnect: [() => {}],
		};

		wtListenOnDisconnect(initState);

		try {
			await initState.transport.ready;
		} catch (oops) {
			triggerDisconnect(initState, { reason: String(oops) });
			throw oops;
		}

		initState.established = true;

		const simulationStream = await transport.createBidirectionalStream();
		stateStream = wtListenForState(simulationStream.readable.getReader());
		const inputStream = simulationStream.writable.getWriter();
		writeInput = function (stateBytes) {
			//write the number of bytes being sent
			const stateSizeBytes = new ArrayBuffer(SIZEOF_32BIT);
			new DataView(stateSizeBytes).setUint32(0, stateBytes.byteLength, true);

			inputStream.write(stateSizeBytes);
			inputStream.write(stateBytes);
		};
	} else {
		const ws = new WebSocket(`wss://${hostname}:${wsPort}`);
		ws.binaryType = "arraybuffer";

		initState = {
			hostname,
			wtPort,
			wsPort,
			transport: ws,
			established: false,
			open: true,
			onDisconnect: [() => {}],
		};

		ws.onclose = function (e) {
			triggerDisconnect(initState, { reason: e.reason, closeCode: e.code });
		};

		await new Promise<void>((resolve) => (ws.onopen = () => resolve()));
		initState.established = true;

		stateStream = wsListenForState(initState);
		writeInput = ws.send.bind(ws);
	}

	if (NET_SIMULATION_PING > 0) {
		const ogWriteInput = writeInput;
		writeInput = async function (chunk) {
			await new Promise((resolve) => setTimeout(resolve, NET_SIMULATION_PING));
			ogWriteInput(chunk);
		};
	}

	//the first packet is needed to init the simulation.
	//it is a snapshot of the current game state
	const newClientSnapshot = (await stateStream.next()).value!;

	return {
		transport: initState.transport,
		newClientSnapshot,
		writeInput,
		stateStream,
		onDisconnect: initState.onDisconnect,
	};
}

//do not await this. it is an infinite loop
export async function onStateReceived(state: State, cb: (stateBuffer: Uint8Array) => void) {
	while (true) cb((await state.stateStream.next()).value!);
}

export function onDisconnect(state: State, cb: () => void) {
	//note this is a tuple so that the change propagates to both
	//the current NetState and the original InitializingNetState
	state.onDisconnect[0] = cb;
}

function triggerDisconnect(state: InitializingNetState, oops: WebTransportCloseInfo) {
	if (!state.open) return;
	state.open = false;
	state.transport.close();

	try {
		state.onDisconnect[0]();
	} catch (oops) {
		//eslint-disable-next-line no-console
		console.error(oops);
	}

	const isWebSocket = state.transport instanceof WebSocket;
	if (isWebSocket && !state.established && import.meta.env.DEV) {
		if (
			confirm(
				"Lost connection to game server. Your browser may be blocking the WSS connection due to the server using self-signed certificates. Click OK to check.",
			)
		) {
			//using setInterval in an attempt to give the browser
			//more time to add the current vite page to its history.
			//sometimes since the page doesn't fully load before this
			//redirect, it doesn't get added. the websocket page
			//attempts to go back 1 page in history after dismissing
			//the cert warning so it needs to be in there
			setInterval(() => (location.href = `https://${state.hostname}:${state.wsPort}`), 500);
		}
	} else {
		oops.reason = oops.reason?.trim(); //sometimes it's nothing but whitespace?
		const reason = oops.reason ? `: ${oops.reason ?? ""}` : "";
		const protocol = isWebSocket ? "WebSocket" : "WebTransport";
		const code = oops.closeCode !== undefined ? ` (${protocol} error code ${oops.closeCode})` : "";
		const full = `Lost connection to game server${reason}${code}`;

		//the tab is now borked. need proper retry handling
		alert(full);
	}
}

//---WEBTRANSPORT---//

//the equivalent "listen_for_input" happens in rust
async function* wtListenForState(stateStream: ReadableStreamDefaultReader) {
	let excess = new Uint8Array();

	while (true) {
		//receive number of bytes in server's simulation state diff
		const stateSizeBytes = await wtReceivePacket(stateStream, SIZEOF_32BIT, excess);
		const stateSize = new DataView(stateSizeBytes.packet.buffer).getUint32(0, true);
		excess = stateSizeBytes.excess;

		const stateBytes = await wtReceivePacket(stateStream, stateSize, excess);
		excess = stateBytes.excess;
		yield stateBytes.packet;
	}
}

async function wtListenOnDisconnect(state: WTInitializingNetState) {
	let closeInfo;
	try {
		closeInfo = await state.transport.closed;
	} catch (oops) {
		closeInfo = { reason: String(oops) };
	}

	triggerDisconnect(state, closeInfo);
}

//stoopid api doesn't let you request to read
//a fixed number of bytes, so prvExcessBuffer
//is needed to hold onto whatever extra bytes
//were uncontrollably vomited
async function wtReceivePacket(
	stream: ReadableStreamDefaultReader,
	size: number,
	prvExcessBuffer: Uint8Array<ArrayBuffer>,
) {
	const packetBuffer = new Uint8Array(size);
	packetBuffer.set(prvExcessBuffer.subarray(0, size));
	let progress = prvExcessBuffer.length;

	let newExcessBuffer: typeof prvExcessBuffer;
	if (progress >= size) {
		newExcessBuffer = prvExcessBuffer.subarray(size);
	} else {
		while (progress < size) {
			if (NET_SIMULATION_PING > 0)
				await new Promise((resolve) => setTimeout(resolve, NET_SIMULATION_PING));

			const result = await stream.read();
			if (result.done) throw Error("State stream closed");

			const needMore = size - progress;
			packetBuffer.set(result.value.subarray(0, needMore), progress);
			progress += result.value.length;

			if (progress >= size) newExcessBuffer = result.value.subarray(needMore);
		}
	}

	return { packet: packetBuffer, excess: newExcessBuffer! };
}

//---WEBSOCKET---//

async function* wsListenForState(state: WSInitializingNetState) {
	//buffer incoming messages so the async generator can yield them on demand
	const queue: Uint8Array[] = [];
	let resolve: (() => void) | null = null;
	let timeout = wsListenOnDisconnect(state);

	state.transport.onmessage = (e: MessageEvent) => {
		queue.push(new Uint8Array(e.data as ArrayBuffer));
		resolve?.();
		resolve = null;

		clearTimeout(timeout);
		timeout = wsListenOnDisconnect(state);
	};

	while (true) {
		if (queue.length === 0) await new Promise<void>((r) => (resolve = r));
		if (NET_SIMULATION_PING > 0) await new Promise((r) => setTimeout(r, NET_SIMULATION_PING));

		yield queue.shift()!;
	}
}

function wsListenOnDisconnect(state: WSInitializingNetState) {
	return setTimeout(() => triggerDisconnect(state, { reason: "Timed out" }), NET_TIMEOUT * 1000);
}
