[package]
name = "borger_rapier"
version.workspace = true
edition.workspace = true

[features]
server = []
client = []

[dependencies]
#note that a plugin lives inside the node_modules folder, and
#you will have to traverse up .. depending on the nodePackageName
borger_plugin_sdk = { path = "../../../borger/plugins/sdk/rs" }

glam.workspace = true

rapier3d = { version = "*", default-features = false, features = ["dim3", "f32", "alloc"] }
